### ISSUE TITLE
class embedding vector for custom data

### ISSUE THREAD

**Issue by chiran7** [sandipan211/ZSD-SC-Resolver#12]
Dear @sandipan211 ,

I have one query regarding class embedding. In the current repository, for MSCOCO, MSCOCO/fasttext.npy, it uses 81300 dimensional embedding , and Pascal VOC, VOC/fasttext_synonym.npy, it uses 21300 dimensional embedding. It may be because 81th in coco and 21st in voc may represent background class.
I want to create similar class embedding for custom data having 50 different number of classes. In that case, is the class embedding (for instance, in VOC/fasttext_synonym.npy) that can represent different categorical name of classes into numerical representation? Is using the python embedding function , such as word2vec , is only to represent the different classes with names in string to numerical value with 300 dimensions for each class ?

The class embedding weight (such as fasttext.npy) is required to train the regressor, specially in step 3.

Thank you for your time and consideration.

**Comment by sandipan211** [comment]
Here is the [link](https://radimrehurek.com/gensim/models/word2vec.html) for a gensim tutorial from where you can make your own class embeddings (word2vec/glove/fasttext) given a class name. DIfferent embedding methods like word2vec and others are tools generated from unsupervised text mining from web corpuses like Wikipedia. Given a class name (string), they can output continuous word vectors.

**NOTE**: In our class embeddings, the background class is represented by the 0th index vector, not the last vector.

**Comment by sqdcbbj** [comment]
Hello, I would like to know if the category name used for background when generating semantic vectors for categories is' background '? For example, I have two categories, cat and dog. Cat is a seen class and dog is an unseen  class. When generating semantic vectors for them,  I use ('background', 'cat', 'dog'), right?

**Comment by sandipan211** [comment]
> Hello, I would like to know if the category name used for background when generating semantic vectors for categories is' background '? For example, I have two categories, cat and dog. Cat is a seen class and dog is an unseen class. When generating semantic vectors for them, I use ('background', 'cat', 'dog'), right?

If you want, you can take that approach. However, performance might be affected since background is quite a vague concept unlike objects like cat and dog, which are well-defined. In our case, we took the semantic vectors from previous work and hence I'm not sure what method they used for obtaining the background semantic (more details can be found from my reply to this [issue](https://github.com/sandipan211/ZSD-SC-Resolver/issues/4#issuecomment-1434447001). 

Even if you would like to get the semantic vectors yourself for custom classes, I would suggest you use the semantic vector given in my repository for the "background" class, and I'm saying this purely for performance reasons.

**Comment by sqdcbbj** [comment]
Thanks!
