### ISSUE TITLE
num_classes for first step

### ISSUE THREAD

**Issue by polyted** [sandipan211/ZSD-SC-Resolver#3]
What should num_classes be for the first step when training on *seen* data?

num_classes=81,

or,
        
num_classes=66,

**Comment by sandipan211** [comment]
num_classes represent the total number of classes to search for a possible label for a detected bounding box (including background). Even while training with seen data only, the Faster-RCNN bbox_head looks to detect all classes (seen+unseen) - however, the unseen classification capabilities of the Faster-RCNN are no better than a random guess (due to the unavailability of unseen visual data). However, after updating Faster-RCNN using generated _unseen class_ features (after Step 5, see [README.md](https://github.com/sandipan211/ZSD-SC-Resolver/blob/main/README.md)), the ability of unseen detection is gained. Hence, **num_classes = (number of seen+unseen classes) + 1**

**Comment by polyted** [comment]
Very helpful, a related question: 

In step 3:

cd ./mmdetection
python tools/zero_shot_utils.py configs/faster_rcnn_r101_fpn_1x.py --classes seen --load_from ./work_dirs/coco2014/epoch_12.pth --save_dir ./data --data_split train

A train_0.6_0.3_feats.npy file is generated OK. How to modify this command to generate a test_0.6_0.3_feats.npy that is required for the step 5:

./script/train_coco_generator_65_15.sh

It refuses to run to completion without a test_0.6_0.3_feats.npy file also being available.

**Comment by sandipan211** [comment]
@polyted here is the command to run for generating test_0.6_0.3_feats.npy:

cd ./mmdetection
python tools/zero_shot_utils.py configs/faster_rcnn_r101_fpn_1x.py --classes unseen --load_from ./work_dirs/coco2014/epoch_12.pth --save_dir ./data --data_split test

Closing this issue since the problem seems to be resolved.
