### ISSUE TITLE
Confusion about validation metrics for zero-shot detection.

### ISSUE THREAD

**Issue by Tavarich** [sandipan211/ZSD-SC-Resolver#9]
Hi, I am now a bit confused about validation metrics for zero-shot detection.

I knew zsd is that just load unseen classes whlie test, and we just setting **classes_to_load as unseen** is ok. And I repeat the result as you reported on coco and voc dataset.

How do I test gzsd setting?  Does gzsd means load all classes while test(**classes_to_load = all**)? In mmdetection/tools/test.py, this code may set for gzsd test on coco.
```
 if cfg.test_cfg.rcnn.gzsd and hasattr(dataset,'cat_ids'):
        dataset.cat_to_load = dataset.cat_ids
```
When I test gzsd (use --gzsd) on voc, I can't get gzsd result. When I test gzsd on coco dataset, I get a worse result, which is different to your report.
**So, for gzsd, how to load the correct test data on both voc and coco dataset?**

Hope you can answer my confusion, thank you very much！

**Comment by Tavarich** [comment]
Hi, I may found the reason on why I can't repeat the gzsd result on coco dataset.

The problem should be here: [test_mixins.py](https://github.com/sandipan211/ZSD-SC-Resolver/blob/f331f1ed69f2dfae94test_mixins.pyeeb4de45b5aeb654ece818/mmdetection/mmdet/models/detectors/test_mixins.py#L67). Code below should change 21 to 81 for coco dataset.
`
  seen_class_inds_bg = np.concatenate(
            ([21], seen_class_inds))  # for code change it to 81 , and for voc set it as 21
`

**But I still have no idea about how to get gzsd result for VOC dataset (how to load the correct test data on voc for gzsd setting?). Hope you can answer it, Thanks so much.**

**Comment by sandipan211** [comment]
Hi,

There has been an inconsistency in the comments we wrote. For VOC, GZSD is not defined in zero-shot detection literature, probably due to the way seen and unseen datasets are obtained from VOC 2007/12. This is why you can see we have not reported the harmonic mean for GZSD for VOC in our paper. Table 3 only reports seen and unseen mAP separately.

ZSD as a field has not been standardized yet, like zero-shot classification, where standard evaluation protocols are strictly defined for ZSL and GZSL. We have followed [1] for evaluation protocols w.r.t VOC. You can read their evaluation protocols to know more about testing with VOC.

[1]  Shafin Rahman, Salman Khan, and Nick Barnes. Polarity loss for zero-shot object detection. arXiv preprint arXiv:1811.08982, 2018

**Comment by Tavarich** [comment]
Thank you for your reply! I observed that some papers didn't report gzsd result for voc dataset (maybe some other paper did). And I got the result of Table 3 (use gzsd setting to test seen and unseen separately). Nevertheless, I'm sure your work is very solid, thanks

**Comment by EfaJow** [comment]
Hi @Tavarich,
Did you change the code in test_mixins.py from 21 to 81?
`seen_class_inds_bg = np.concatenate( ([21], seen_class_inds))  # for code change it to 81 , and for voc set it as 21`
Could you share how did you get the right mAP result (0.374 for seen and 0.201 for unseen) in GZSL? 
I changed 21 to 81, but the mAP didn't go right.
